-- =======================================================
-- Database Schema Migration: Audit Logs Table
-- =======================================================

-- 1. Create audit_logs table
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  action text not null,
  target_id text,
  user_id uuid references public.profiles(id) on delete set null,
  user_email text not null,
  metadata jsonb default '{}'::jsonb not null
);

-- Enable Row Level Security (RLS)
alter table public.audit_logs enable row level security;

-- 2. RLS Policies for audit_logs
-- Allow any authenticated user to insert log events (e.g. logging their own post creation/deletion)
create policy "Allow authenticated users to insert audit_logs" on public.audit_logs
  for insert with check (auth.role() = 'authenticated');

-- Allow only admins and moderators to read audit logs
create policy "Allow admins and moderators to view audit_logs" on public.audit_logs
  for select using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('admin', 'moderator')
    )
  );
