-- =======================================================
-- Database Schema Migration: Event-Driven Architecture (EDA)
-- =======================================================

-- 1. Create event_store table (Transaction Ledger)
create table if not exists public.event_store (
  id uuid primary key default gen_random_uuid(),
  event_type text not null, -- e.g. 'post.created', 'comment.created', 'post.liked', 'user.followed'
  payload jsonb default '{}'::jsonb not null,
  actor_id uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Event Store (Read-only for Admins/Audit, system writes)
alter table public.event_store enable row level security;

drop policy if exists "Allow admins and audit roles to select event_store" on public.event_store;
create policy "Allow admins and audit roles to select event_store" on public.event_store
  for select using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

drop policy if exists "Allow authenticated users to insert event_store" on public.event_store;
create policy "Allow authenticated users to insert event_store" on public.event_store
  for insert with check (true);

-- 2. Create event_queue table (Transactional Outbox Queue)
create table if not exists public.event_queue (
  id bigint generated by default as identity primary key,
  event_id uuid references public.event_store(id) on delete cascade not null,
  status text default 'pending' not null check (status in ('pending', 'processing', 'completed', 'failed')),
  attempts integer default 0 not null,
  max_attempts integer default 5 not null,
  error_message text,
  process_after timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Event Queue (Read-only for Admins)
alter table public.event_queue enable row level security;

drop policy if exists "Allow admins to select event_queue" on public.event_queue;
create policy "Allow admins to select event_queue" on public.event_queue
  for select using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

drop policy if exists "Allow authenticated users to insert event_queue" on public.event_queue;
create policy "Allow authenticated users to insert event_queue" on public.event_queue
  for insert with check (true);

-- 3. Trigger to automatically enqueue new events from the event store
create or replace function public.enqueue_new_event()
returns trigger as $$
begin
  insert into public.event_queue (event_id)
  values (new.id);
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger trigger_enqueue_new_event
  after insert on public.event_store
  for each row execute procedure public.enqueue_new_event();

-- 4. Central event publishing helper function
create or replace function public.publish_event(
  p_event_type text,
  p_payload jsonb,
  p_actor_id uuid
)
returns uuid as $$
declare
  v_event_id uuid;
begin
  insert into public.event_store (event_type, payload, actor_id)
  values (p_event_type, p_payload, p_actor_id)
  returning id into v_event_id;
  
  return v_event_id;
end;
$$ language plpgsql security definer;

-- 5. Set up triggers on operational tables to automatically publish events
-- A. Posts Trigger
create or replace function public.publish_post_event()
returns trigger as $$
begin
  if tg_op = 'INSERT' then
    perform public.publish_event(
      'post.created',
      jsonb_build_object(
        'id', new.id,
        'title', new.title,
        'user_id', new.user_id,
        'created_at', new.created_at
      ),
      new.user_id
    );
  end if;
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger tr_publish_post_event
  after insert on public.posts
  for each row execute procedure public.publish_post_event();

-- B. Comments Trigger
create or replace function public.publish_comment_event()
returns trigger as $$
begin
  if tg_op = 'INSERT' then
    perform public.publish_event(
      'comment.created',
      jsonb_build_object(
        'id', new.id,
        'post_id', new.post_id,
        'user_id', new.user_id,
        'content', new.content,
        'created_at', new.created_at
      ),
      new.user_id
    );
  end if;
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger tr_publish_comment_event
  after insert on public.comments
  for each row execute procedure public.publish_comment_event();

-- C. Likes Trigger
create or replace function public.publish_like_event()
returns trigger as $$
begin
  if tg_op = 'INSERT' then
    perform public.publish_event(
      'post.liked',
      jsonb_build_object(
        'id', new.id,
        'post_id', new.post_id,
        'user_id', new.user_id,
        'created_at', new.created_at
      ),
      new.user_id
    );
  end if;
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger tr_publish_like_event
  after insert on public.likes
  for each row execute procedure public.publish_like_event();

-- D. Follows Trigger
create or replace function public.publish_follow_event()
returns trigger as $$
begin
  if tg_op = 'INSERT' then
    perform public.publish_event(
      'user.followed',
      jsonb_build_object(
        'id', new.id,
        'follower_id', new.follower_id,
        'following_id', new.following_id,
        'created_at', new.created_at
      ),
      new.follower_id
    );
  end if;
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger tr_publish_follow_event
  after insert on public.follows
  for each row execute procedure public.publish_follow_event();

-- =======================================================
-- Transition from Synchronous to Asynchronous Processing
-- =======================================================

-- Disable old synchronous reputation triggers
alter table public.posts disable trigger on_post_reputation;
alter table public.comments disable trigger on_comment_reputation;
alter table public.likes disable trigger on_like_reputation;
alter table public.follows disable trigger on_follow_reputation;

-- Disable old synchronous activity log triggers
alter table public.posts disable trigger tr_post_creation_activity;
alter table public.comments disable trigger tr_comment_creation_activity;
alter table public.likes disable trigger tr_like_activity;
alter table public.follows disable trigger tr_follow_activity;

-- =======================================================
-- Asynchronous Queue Processor & Outbox Handlers
-- =======================================================

-- Asynchronous handlers (executed by outbox consumer)
create or replace function public.handle_async_event(
  p_event_type text,
  p_payload jsonb,
  p_actor_id uuid
)
returns void as $$
declare
  v_full_name text;
  v_post_title text;
  v_post_author_id uuid;
  v_following_name text;
begin
  -- 1. Asynchronous Gamification & Activity Feed logic based on Event Type
  if p_event_type = 'post.created' then
    -- A. Update reputation +10
    update public.profiles set reputation_points = reputation_points + 10 where id = p_actor_id;
    perform public.check_user_badges(p_actor_id);
    
    -- B. Add activity log
    select full_name into v_full_name from public.profiles where id = p_actor_id;
    insert into public.activities (actor_id, action_type, target_id, description, metadata)
    values (
      p_actor_id,
      'post.create',
      p_payload->>'id',
      coalesce(v_full_name, 'A user') || ' published a new post: "' || substring(p_payload->>'title' from 1 for 50) || '"',
      jsonb_build_object('post_id', p_payload->>'id', 'title', p_payload->>'title')
    );

  elsif p_event_type = 'comment.created' then
    -- A. Update reputation +5
    update public.profiles set reputation_points = reputation_points + 5 where id = p_actor_id;
    perform public.check_user_badges(p_actor_id);

    -- B. Add activity log
    select full_name into v_full_name from public.profiles where id = p_actor_id;
    select title into v_post_title from public.posts where id = (p_payload->>'post_id')::bigint;
    insert into public.activities (actor_id, action_type, target_id, description, metadata)
    values (
      p_actor_id,
      'comment.create',
      p_payload->>'post_id',
      coalesce(v_full_name, 'A user') || ' commented on "' || coalesce(v_post_title, 'a post') || '": "' || substring(p_payload->>'content' from 1 for 40) || '..."',
      jsonb_build_object('post_id', p_payload->>'post_id', 'comment_id', p_payload->>'id', 'post_title', v_post_title)
    );

  elsif p_event_type = 'post.liked' then
    -- A. Update reputation +5 for post author
    select user_id into v_post_author_id from public.posts where id = (p_payload->>'post_id')::bigint;
    if v_post_author_id is not null then
      update public.profiles set reputation_points = reputation_points + 5 where id = v_post_author_id;
      perform public.check_user_badges(v_post_author_id);
    end if;

    -- B. Add activity log
    select full_name into v_full_name from public.profiles where id = p_actor_id;
    select title into v_post_title from public.posts where id = (p_payload->>'post_id')::bigint;
    insert into public.activities (actor_id, action_type, target_id, description, metadata)
    values (
      p_actor_id,
      'post.like',
      p_payload->>'post_id',
      coalesce(v_full_name, 'A user') || ' liked the post: "' || coalesce(v_post_title, 'Untitled') || '"',
      jsonb_build_object('post_id', p_payload->>'post_id', 'post_title', v_post_title)
    );

  elsif p_event_type = 'user.followed' then
    -- A. Update reputation +2 for follower
    update public.profiles set reputation_points = reputation_points + 2 where id = p_actor_id;
    perform public.check_user_badges(p_actor_id);

    -- B. Add activity log
    select full_name into v_full_name from public.profiles where id = p_actor_id;
    select full_name into v_following_name from public.profiles where id = (p_payload->>'following_id')::uuid;
    insert into public.activities (actor_id, action_type, target_id, description, metadata)
    values (
      p_actor_id,
      'user.follow',
      p_payload->>'following_id',
      coalesce(v_full_name, 'A user') || ' started following ' || coalesce(v_following_name, 'another user'),
      jsonb_build_object('following_id', p_payload->>'following_id', 'following_name', v_following_name)
    );
  end if;
end;
$$ language plpgsql security definer;

-- 6. Central Asynchronous Queue Consumer Function
-- Grabs pending items, marks them, routes them, and updates their final status.
create or replace function public.process_event_queue(p_batch_size integer default 10)
returns table (
  processed_count integer,
  failed_count integer
) as $$
declare
  v_item record;
  v_processed integer := 0;
  v_failed integer := 0;
begin
  -- Loop through pending event queue items
  for v_item in 
    select q.id, q.attempts, s.event_type, s.payload, s.actor_id 
    from public.event_queue q
    join public.event_store s on q.event_id = s.id
    where q.status in ('pending', 'failed')
      and q.attempts < q.max_attempts
      and q.process_after <= timezone('utc'::text, now())
    order by q.created_at asc
    limit p_batch_size
    for update skip locked -- Prevent concurrent workers from picking the same items (optimistic locking)
  loop
    begin
      -- Mark item as processing
      update public.event_queue
      set status = 'processing',
          attempts = attempts + 1,
          updated_at = timezone('utc'::text, now())
      where id = v_item.id;

      -- Execute handlers asynchronously
      perform public.handle_async_event(v_item.event_type, v_item.payload, v_item.actor_id);

      -- Mark completed
      update public.event_queue
      set status = 'completed',
          updated_at = timezone('utc'::text, now())
      where id = v_item.id;
      
      v_processed := v_processed + 1;

    exception when others then
      -- Log error and mark failed with backoff delay (attempts * 1 minute delay)
      update public.event_queue
      set status = 'failed',
          error_message = SQLERRM,
          process_after = timezone('utc'::text, now()) + (attempts * interval '1 minute'),
          updated_at = timezone('utc'::text, now())
      where id = v_item.id;
      
      v_failed := v_failed + 1;
    end;
  end loop;

  processed_count := v_processed;
  failed_count := v_failed;
  return next;
end;
$$ language plpgsql security definer;
