-- =======================================================
-- Database Schema Migration: Realtime Activity Feed
-- =======================================================

-- 1. Create activities table
create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  actor_id uuid references public.profiles(id) on delete cascade not null,
  action_type text not null, -- 'post.create', 'post.like', 'comment.create', 'user.follow', 'profile.update'
  target_id text,
  description text not null,
  metadata jsonb default '{}'::jsonb not null
);

-- Enable Row Level Security (RLS)
alter table public.activities enable row level security;

-- RLS Policies for activities
-- Allow public select access so anyone on the platform can see the activity timeline
create policy "Allow public read access to activities" on public.activities
  for select using (true);

-- Allow authenticated users to write activities directly if necessary
create policy "Allow authenticated users to insert activities" on public.activities
  for insert with check (auth.uid() = actor_id);

-- Configure Replica Identity to FULL for deletes
alter table public.activities replica identity full;

-- Enable Realtime Broadcasting
alter publication supabase_realtime add table public.activities;


-- =======================================================
-- Trigger Functions for Automatic Activity Tracking
-- =======================================================

-- A. Trigger for Post Creation
create or replace function public.log_post_creation_activity()
returns trigger as $$
declare
  v_full_name text;
begin
  select full_name into v_full_name from public.profiles where id = new.user_id;
  
  insert into public.activities (actor_id, action_type, target_id, description, metadata)
  values (
    new.user_id,
    'post.create',
    new.id::text,
    coalesce(v_full_name, 'A user') || ' published a new post: "' || substring(new.title from 1 for 50) || '"',
    jsonb_build_object('post_id', new.id, 'title', new.title)
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger tr_post_creation_activity
  after insert on public.posts
  for each row execute procedure public.log_post_creation_activity();


-- B. Trigger for Comment Creation
create or replace function public.log_comment_creation_activity()
returns trigger as $$
declare
  v_full_name text;
  v_post_title text;
begin
  select full_name into v_full_name from public.profiles where id = new.user_id;
  select title into v_post_title from public.posts where id = new.post_id;
  
  insert into public.activities (actor_id, action_type, target_id, description, metadata)
  values (
    new.user_id,
    'comment.create',
    new.post_id::text,
    coalesce(v_full_name, 'A user') || ' commented on "' || coalesce(v_post_title, 'a post') || '": "' || substring(new.content from 1 for 40) || '..."',
    jsonb_build_object('post_id', new.post_id, 'comment_id', new.id, 'post_title', v_post_title)
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger tr_comment_creation_activity
  after insert on public.comments
  for each row execute procedure public.log_comment_creation_activity();


-- C. Trigger for Liking Posts
create or replace function public.log_like_activity()
returns trigger as $$
declare
  v_full_name text;
  v_post_title text;
begin
  select full_name into v_full_name from public.profiles where id = new.user_id;
  select title into v_post_title from public.posts where id = new.post_id;
  
  insert into public.activities (actor_id, action_type, target_id, description, metadata)
  values (
    new.user_id,
    'post.like',
    new.post_id::text,
    coalesce(v_full_name, 'A user') || ' liked the post: "' || coalesce(v_post_title, 'Untitled') || '"',
    jsonb_build_object('post_id', new.post_id, 'post_title', v_post_title)
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger tr_like_activity
  after insert on public.likes
  for each row execute procedure public.log_like_activity();


-- D. Trigger for User Follows
create or replace function public.log_follow_activity()
returns trigger as $$
declare
  v_follower_name text;
  v_following_name text;
begin
  select full_name into v_follower_name from public.profiles where id = new.follower_id;
  select full_name into v_following_name from public.profiles where id = new.following_id;
  
  insert into public.activities (actor_id, action_type, target_id, description, metadata)
  values (
    new.follower_id,
    'user.follow',
    new.following_id::text,
    coalesce(v_follower_name, 'A user') || ' started following ' || coalesce(v_following_name, 'another user'),
    jsonb_build_object('following_id', new.following_id, 'following_name', v_following_name)
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger tr_follow_activity
  after insert on public.follows
  for each row execute procedure public.log_follow_activity();


-- E. Trigger for Profile Updates
create or replace function public.log_profile_update_activity()
returns trigger as $$
begin
  -- Trigger only on display name or username changes
  if (old.full_name is distinct from new.full_name or old.username is distinct from new.username) then
    insert into public.activities (actor_id, action_type, description, metadata)
    values (
      new.id,
      'profile.update',
      coalesce(new.full_name, new.username, 'A user') || ' updated their profile details.',
      jsonb_build_object('full_name', new.full_name, 'username', new.username)
    );
  end if;
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger tr_profile_update_activity
  after update on public.profiles
  for each row execute procedure public.log_profile_update_activity();
