-- =======================================================
-- Database Schema Migration: Content Reporting & Moderation
-- =======================================================

-- 1. Add deleted_at column to comments to support soft deletion
alter table public.comments add column if not exists deleted_at timestamp with time zone;

-- Adjust select policy for comments to respect soft deletes
drop policy if exists "Allow public read access to comments" on public.comments;
drop policy if exists "Allow public read access to active comments" on public.comments;

create policy "Allow public read access to active comments" on public.comments
  for select using (
    deleted_at is null 
    or auth.uid() = user_id 
    or exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('admin', 'moderator')
    )
  );

-- 2. Create reports table
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  reporter_id uuid references public.profiles(id) on delete set null not null,
  content_type text not null check (content_type in ('post', 'comment')),
  content_id bigint not null,
  reason text not null check (reason in ('spam', 'hate_speech', 'harassment', 'inappropriate', 'other')),
  description text,
  status text default 'pending' not null check (status in ('pending', 'resolved', 'dismissed')),
  resolved_by uuid references public.profiles(id) on delete set null,
  resolved_at timestamp with time zone
);

-- Enable Row Level Security (RLS)
alter table public.reports enable row level security;

-- 3. RLS Policies for reports
-- Allow authenticated users to create reports
create policy "Allow authenticated users to insert reports" on public.reports
  for insert with check (auth.uid() = reporter_id);

-- Allow only admins and moderators to read reports
create policy "Allow admins and moderators to select reports" on public.reports
  for select using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('admin', 'moderator')
    )
  );

-- Allow only admins and moderators to update reports (change status, resolve)
create policy "Allow admins and moderators to update reports" on public.reports
  for update using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('admin', 'moderator')
    )
  );

-- Configure Replica Identity to FULL for Realtime support
alter table public.reports replica identity full;

-- Enable Realtime Broadcasting
alter publication supabase_realtime add table public.reports;
