-- =======================================================
-- Database Schema Migration: Comments & Likes Tables
-- =======================================================

-- 1. Create comments table
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone,
  content text not null,
  post_id bigint references public.posts(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null
);

-- Enable Row Level Security (RLS) for comments
alter table public.comments enable row level security;

-- RLS Policies for comments
create policy "Allow public read access to comments" on public.comments
  for select using (true);

create policy "Allow authenticated users to insert comments" on public.comments
  for insert with check (auth.uid() = user_id);

create policy "Allow users to update their own comments" on public.comments
  for update using (auth.uid() = user_id);

create policy "Allow users to delete their own comments" on public.comments
  for delete using (auth.uid() = user_id);


-- 2. Create likes table (Many-to-Many Relationship)
create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  post_id bigint references public.posts(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  
  -- Duplicate Prevention: Ensure a profile can only like a post once
  constraint unique_post_user_like unique (post_id, user_id)
);

-- Enable Row Level Security (RLS) for likes
alter table public.likes enable row level security;

-- RLS Policies for likes
create policy "Allow public read access to likes" on public.likes
  for select using (true);

create policy "Allow authenticated users to insert likes" on public.likes
  for insert with check (auth.uid() = user_id);

create policy "Allow users to delete their own likes" on public.likes
  for delete using (auth.uid() = user_id);

-- Configure Replica Identity to FULL so that DELETE realtime payloads contain user_id and post_id
alter table public.likes replica identity full;

-- 3. Enable Realtime Broadcasting
alter publication supabase_realtime add table public.likes;
alter publication supabase_realtime add table public.comments;


-- 4. Create bookmarks table (Relationship Table)
create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  post_id bigint references public.posts(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  
  -- Duplicate Prevention: Ensure a user can only bookmark a post once
  constraint unique_post_user_bookmark unique (post_id, user_id)
);

-- Enable Row Level Security (RLS) for bookmarks
alter table public.bookmarks enable row level security;

-- RLS Policies for bookmarks (Private: Only the bookmark owner can read their own bookmarks)
create policy "Allow users to view their own bookmarks" on public.bookmarks
  for select using (auth.uid() = user_id);

create policy "Allow authenticated users to insert bookmarks" on public.bookmarks
  for insert with check (auth.uid() = user_id);

create policy "Allow users to delete their own bookmarks" on public.bookmarks
  for delete using (auth.uid() = user_id);

-- Configure Replica Identity to FULL so that DELETE realtime payloads contain user_id and post_id
alter table public.bookmarks replica identity full;

-- Enable Realtime Broadcasting for Bookmarks
alter publication supabase_realtime add table public.bookmarks;


-- 5. Create notifications table
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  recipient_id uuid references public.profiles(id) on delete cascade not null,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  type text not null, -- 'like', 'comment', or 'follow'
  post_id bigint references public.posts(id) on delete cascade,
  is_read boolean default false not null
);

-- Enable Row Level Security (RLS) for notifications
alter table public.notifications enable row level security;

-- RLS Policies for notifications (Private: Only the recipient can read and update their own notifications)
create policy "Allow users to view their own notifications" on public.notifications
  for select using (auth.uid() = recipient_id);

create policy "Allow authenticated users to insert notifications" on public.notifications
  for insert with check (auth.uid() = sender_id);

create policy "Allow users to update their own notifications" on public.notifications
  for update using (auth.uid() = recipient_id);

-- Configure Replica Identity to FULL
alter table public.notifications replica identity full;

-- Enable Realtime Broadcasting for Notifications
alter publication supabase_realtime add table public.notifications;


-- 6. Create follows table (Self-referencing Many-to-Many Relationship)
create table if not exists public.follows (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  follower_id uuid references public.profiles(id) on delete cascade not null,
  following_id uuid references public.profiles(id) on delete cascade not null,
  
  -- Prevent users from following themselves
  constraint check_not_self_follow check (follower_id <> following_id),
  -- Prevent duplicate follow entries
  constraint unique_follower_following unique (follower_id, following_id)
);

-- Enable Row Level Security (RLS) for follows
alter table public.follows enable row level security;

-- RLS Policies for follows
create policy "Allow public read access to follows" on public.follows
  for select using (true);

create policy "Allow authenticated users to insert follows" on public.follows
  for insert with check (auth.uid() = follower_id);

create policy "Allow users to delete their own follows" on public.follows
  for delete using (auth.uid() = follower_id);

-- Configure Replica Identity to FULL
alter table public.follows replica identity full;

-- Enable Realtime Broadcasting for Follows
alter publication supabase_realtime add table public.follows;

-- 7. Indexes for Query Optimization
create index if not exists idx_posts_user_id on public.posts(user_id);
create index if not exists idx_follows_follower_id on public.follows(follower_id);
create index if not exists idx_follows_following_id on public.follows(following_id);

-- 8. Add last_seen to profiles table
alter table public.profiles add column if not exists last_seen timestamp with time zone default timezone('utc'::text, now());

-- 9. Create user_settings and notification_preferences tables
create table if not exists public.user_settings (
  user_id uuid references public.profiles(id) on delete cascade primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  theme text default 'dark' not null,
  is_private_profile boolean default false not null
);

alter table public.user_settings enable row level security;
create policy "Allow users to view their own settings" on public.user_settings
  for select using (auth.uid() = user_id);
create policy "Allow users to update their own settings" on public.user_settings
  for update using (auth.uid() = user_id);

create table if not exists public.notification_preferences (
  user_id uuid references public.profiles(id) on delete cascade primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email_notifications boolean default true not null,
  push_notifications boolean default true not null,
  like_alerts boolean default true not null,
  comment_alerts boolean default true not null,
  follow_alerts boolean default true not null
);

alter table public.notification_preferences enable row level security;
create policy "Allow users to view their own preferences" on public.notification_preferences
  for select using (auth.uid() = user_id);
create policy "Allow users to update their own preferences" on public.notification_preferences
  for update using (auth.uid() = user_id);

-- 10. Database function and trigger for automatic user initialization after signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  -- 1. Create public profile
  insert into public.profiles (id, full_name, username, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'avatar_url', null)
  );

  -- 2. Create user settings row
  insert into public.user_settings (user_id)
  values (new.id);

  -- 3. Create notification preferences row
  insert into public.notification_preferences (user_id)
  values (new.id);

  return new;
end;
$$ language plpgsql security definer;

-- Trigger to execute function after a row is inserted in auth.users
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 11. Role security triggers and moderation policies
alter table public.profiles add column if not exists role text default 'user' not null;
alter table public.profiles add column if not exists is_banned boolean default false not null;

-- Trigger function to prevent standard users from upgrading their own role or unbanning themselves
create or replace function public.check_role_modification()
returns trigger as $$
begin
  if (old.role <> new.role or old.is_banned <> new.is_banned) then
    if auth.uid() is not null and not exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    ) then
      raise exception 'Unauthorized: Only administrators can modify user roles or ban status.';
    end if;
  end if;
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger trigger_check_role_modification
  before update on public.profiles
  for each row execute procedure public.check_role_modification();

-- Policies to allow administrators and moderators to delete any post or comment
create policy "Allow admins and moderators to delete any post" on public.posts
  for delete using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('admin', 'moderator')
    )
  );

create policy "Allow admins and moderators to delete any comment" on public.comments
  for delete using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('admin', 'moderator')
    )
  );
